# Generated by Django 4.1.3 on 2022-11-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEmprendimiento', models.CharField(choices=[('hospedaje', 'Hospedaje'), ('restaurante', 'Restaurante'), ('paradaTuristica', 'Paradas Turisticas')], max_length=20, verbose_name='Tipo de emprendimiento')),
                ('nombreEmprendiento', models.CharField(max_length=500, verbose_name='Nombre del Emprendimiento')),
                ('direccionEmprendiento', models.CharField(max_length=500, verbose_name='Direccion')),
                ('telCelular', models.CharField(max_length=13, verbose_name='Telefono celular')),
                ('telFijo', models.CharField(max_length=13, verbose_name='Telefono Fijo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('horaApertura', models.DateTimeField()),
                ('horaCierre', models.DateTimeField()),
                ('latitud', models.CharField(max_length=50, verbose_name='Latitud')),
                ('altitud', models.CharField(max_length=50, verbose_name='Altitud')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cedula'), ('pasaporte', 'Pasaporte')], max_length=20, verbose_name='Tipo de documento')),
                ('cedula', models.CharField(max_length=13, verbose_name='Cedula')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('correoElectronico', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('telefono', models.CharField(max_length=13, verbose_name='Numero de telefono')),
                ('direccion', models.CharField(max_length=500, verbose_name='Direccion')),
                ('fechaNacmiento', models.DateField(verbose_name='Fecha de Nacmiento')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotosUsuarios', verbose_name='Subir su foto de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('fechaInicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fechaActualizacion', models.DateTimeField(verbose_name='Fecha de actualizacion')),
                ('estado', models.BooleanField()),
            ],
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('paisOrigen', models.CharField(max_length=200, verbose_name='Pais de origen')),
            ],
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
            ],
            bases=('administracion.persona',),
        ),
    ]
