# Generated by Django 4.1.3 on 2022-12-06 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, null=True, unique=True)),
                ('tipo_documento', models.CharField(blank=True, choices=[('cedula', 'Cedula'), ('pasaporte', 'Pasaporte')], max_length=20, null=True, verbose_name='Tipo de documento')),
                ('cedula', models.CharField(max_length=13, verbose_name='Cedula')),
                ('firstName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('lastName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=13, verbose_name='Numero de telefono')),
                ('direccion', models.CharField(max_length=500, verbose_name='Direccion')),
                ('fechaNacmiento', models.DateField(verbose_name='Fecha de Nacmiento')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotosUsuarios', verbose_name='Subir su foto de usuario')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(max_length=6, verbose_name='Precio')),
                ('descripcionServicio', models.CharField(max_length=500, verbose_name='Descripcion del Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('fechaInicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fechaActualizacion', models.DateTimeField(verbose_name='Fecha de actualizacion')),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('paisOrigen', models.CharField(max_length=200, verbose_name='Pais de origen')),
            ],
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaLlegada', models.DateField(verbose_name='Ingrese la fecha de llegada')),
                ('fechaSalida', models.DateField(verbose_name='Ingrese la fecha de salida')),
                ('numPersonas', models.IntegerField(verbose_name='Ingrese el numero de personas')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Alguna descripcion al momento de la reserva')),
                ('productos', models.ManyToManyField(to='administracion.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmprendiento', models.CharField(max_length=500, verbose_name='Nombre del Emprendimiento')),
                ('direccionEmprendiento', models.CharField(max_length=500, verbose_name='Direccion')),
                ('telCelular', models.CharField(max_length=13, verbose_name='Telefono celular')),
                ('telFijo', models.CharField(max_length=13, verbose_name='Telefono Fijo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('horaApertura', models.DateTimeField()),
                ('horaCierre', models.DateTimeField()),
                ('latitud', models.CharField(max_length=50, verbose_name='Latitud')),
                ('altitud', models.CharField(max_length=50, verbose_name='Altitud')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotosEmprendimiento', verbose_name='Subir su foto del emprendimiento')),
                ('video', models.URLField(blank=True, null=True, verbose_name='video promocional')),
                ('disponibilidad', models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], max_length=3, null=True, verbose_name='Disponibilidad')),
                ('calificacion', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('malo', 'Malo'), ('regular', 'Regular'), ('normal', 'Normal'), ('excelentes', 'Excelente')], max_length=20, null=True, verbose_name='Calificacion')),
                ('resena', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resena')),
                ('servicios', models.ManyToManyField(to='administracion.servicios')),
            ],
            options={
                'verbose_name': 'Emprendiento',
                'verbose_name_plural': 'Emprendientos',
            },
        ),
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('emprendimientos', models.ManyToManyField(blank=True, to='administracion.emprendimiento')),
            ],
            options={
                'verbose_name': 'Emprendedor',
                'verbose_name_plural': 'Emprendedores',
            },
            bases=('administracion.persona',),
        ),
    ]
