# Generated by Django 4.1.3 on 2022-12-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Imagenes del emprendimiento', verbose_name='Subir imagenes del emprendimiento')),
                ('video', models.URLField(blank=True, null=True, verbose_name='video promocional')),
            ],
        ),
        migrations.RemoveField(
            model_name='emprendimiento',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='emprendimiento',
            name='video',
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='producto',
            field=models.ManyToManyField(to='administracion.productos'),
        ),
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion del producto'),
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes del producto', verbose_name='Subir imagenes del producto'),
        ),
        migrations.AddField(
            model_name='productos',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Precio del producto unitario'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='tipoServicio',
            field=models.CharField(blank=True, choices=[('ventaProductos', 'Venta de productos'), ('servicioRestaurante', 'Alojamiento'), ('produccionProductos', 'Produccion de productos'), ('atractivoTuristico', 'Atractivo Turistico'), ('hospedaje', 'Hospedaje'), ('cafeteria', 'Cafeteria'), ('piscina', 'Piscina'), ('camping', 'Camping'), ('caminata', 'Caminata'), ('cabalgata', 'Cabalgata'), ('recreacion', 'Recreacion'), ('comidaTipica', 'Comida Tipica'), ('comidaRapida', 'Comida Rapida'), ('comidaCoreana', 'Comida Coreana')], max_length=20, null=True, verbose_name='Tipo de servicio'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='precio',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='multimedia',
            field=models.ManyToManyField(to='administracion.multimedia'),
        ),
    ]
