# Generated by Django 4.1.3 on 2022-11-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaLlegada', models.DateField(verbose_name='Ingrese la fecha de llegada')),
                ('fechaSalida', models.DateField(verbose_name='Ingrese la fecha de salida')),
                ('numPersonas', models.IntegerField(verbose_name='Ingrese el numero de personas')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Alguna descripcion al momento de la reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=500, verbose_name='Nombre del Servicio')),
                ('tipoServicio', models.CharField(choices=[('ventaProductos', 'Venta de productos'), ('servicioRestaurante', 'Alojamiento'), ('produccionProductos', 'Produccion de productos'), ('atractivoTuristico', 'Atractivo Turistico'), ('hospedaje', 'Hospedaje'), ('cafeteria', 'Cafeteria'), ('piscina', 'Piscina'), ('camping', 'Camping'), ('caminata', 'Caminata'), ('cabalgata', 'Cabalgata'), ('recreacion', 'Recreacion'), ('comidaTipica', 'Comida Tipica'), ('comidaRapida', 'Comida Rapida'), ('comidaCoreana', 'Comida Coreana')], max_length=20, verbose_name='Tipo de servicio')),
                ('resena', models.CharField(max_length=500, verbose_name='Resena')),
                ('calificacion', models.CharField(choices=[('bueno', 'Bueno'), ('malo', 'Malo'), ('regular', 'Regular'), ('normal', 'Normal'), ('excelentes', 'Excelente')], max_length=20, verbose_name='Calificacion')),
                ('precio', models.CharField(max_length=6, verbose_name='Precio')),
                ('disponibilidad', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=3, verbose_name='disponibilidad')),
                ('descripcionServicio', models.CharField(max_length=500, verbose_name='Descripcion del Servicio')),
            ],
        ),
        migrations.RemoveField(
            model_name='emprendimiento',
            name='tipoEmprendimiento',
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotosEmprendimiento', verbose_name='Subir su foto del emprendimiento'),
        ),
    ]
