# Generated by Django 4.1.3 on 2022-12-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_multimedia_remove_emprendimiento_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del rol', max_length=80, verbose_name='Ingresar el nombre del rol')),
                ('descripcion', models.TextField(help_text='Descripcion del rol', verbose_name='Ingrese una descrición detallada del rol')),
            ],
            options={
                'verbose_name': 'Permiso del sistema',
                'verbose_name_plural': 'Permisos para usuarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.RenameField(
            model_name='emprendimiento',
            old_name='producto',
            new_name='productos',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='precio',
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='altitud',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Altitud'),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='latitud',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitud'),
        ),
    ]
