# Generated by Django 4.1.3 on 2022-11-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_reservas_servicios_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='emprendimiento',
            options={'verbose_name': 'Emprendiento', 'verbose_name_plural': 'Emprendientos'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='video promocional'),
        ),
    ]
