# Generated by Django 4.1.3 on 2022-11-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_emprendedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='emprendimientos',
            field=models.ManyToManyField(blank=True, to='administracion.emprendimiento'),
        ),
    ]
