# Generated by Django 4.1.3 on 2022-12-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_rename_nombreemprendiento_emprendimiento_nombreemprendimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Restaurante', 'Restaurante'), ('Hospedaje', 'Hospedaje'), ('Atraccion', 'Atraccion'), ('Market', 'Market')], max_length=15, null=True, verbose_name='Categoria'),
        ),
    ]
