# Generated by Django 4.1.3 on 2022-11-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_emprendedor_emprendimientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='nombreServicio',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='resena',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='tipoServicio',
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='calificacion',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('malo', 'Malo'), ('regular', 'Regular'), ('normal', 'Normal'), ('excelentes', 'Excelente')], max_length=20, null=True, verbose_name='Calificacion'),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='disponibilidad',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], max_length=3, null=True, verbose_name='Disponibilidad'),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='resena',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Resena'),
        ),
    ]
