# Generated by Django 4.1.3 on 2022-11-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_remove_servicios_calificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='servicios',
            field=models.ManyToManyField(to='administracion.servicios'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='productos',
            field=models.ManyToManyField(to='administracion.productos'),
        ),
    ]
